### ISSUE TITLE
Allow multiple mint denom

### ISSUE THREAD

**Issue by vuong177** [onomyprotocol/reserve#75]

**Comment by DongLieu** [comment]
I get an error when ending an auction

`12:43PM ERR CONSENSUS FAILURE!!! err="invalid coin denominations; nomEUR, nomUSD" module=consensus stack="goroutine 408 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:26 +0x64\[ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()](http://ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2())\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:801 +0x4c\npanic({0x106a82c80?, 0x14001a88970?})\n\t/usr/local/go/src/runtime/panic.go:785 +0xf0\[ngithub.com/cosmos/cosmos-sdk/types.Coin.Add({{0x140066d63d0](http://ngithub.com/cosmos/cosmos-sdk/types.Coin.Add(%7B%7B0x140066d63d0), 0x6}, {0x14001c0d8a0}}, {{0x140066d6c80, 0x6}, {0x14001c0ce60}})\n\t/Users/donglieu/go/pkg/mod/github.com/!dong!lieu/cosmos-sdk@v0.50.8-onomy/types/coin.go:111 +0x198\[ngithub.com/onomyprotocol/reserve/x/vaults/keeper.(*Keeper).Liquidate(0x14001396750](http://ngithub.com/onomyprotocol/reserve/x/vaults/keeper.(*Keeper).Liquidate(0x14001396750), {0x1071049e0, 0x1400222c708}, {{0x140066d6be8, 0x4}, {0x140066d63d0, 0x6}, {0x140015a8950, 0x1, 0x1}, ...}, ...)\n\t/Users/donglieu/112024/reserve/x/vaults/keeper/vault.go:552 +0x388\[ngithub.com/onomyprotocol/reserve/x/auction/keeper.Keeper.handleLiquidation({{0x10711deb8](http://ngithub.com/onomyprotocol/reserve/x/auction/keeper.Keeper.handleLiquidation(%7B%7B0x10711deb8), 0x140019aabe0}, {0x1070c7e80, 0x140005ca550}, {0x10710ac88, 0x1400033e9a0}, {0x1070e1520, 0x14001bebe00}, {0x10710f3c0, 0x140013a6008}, ...}, ...)\n\t/Users/donglieu/112024/reserve/x/auction/keeper/liquidate.go:70 +0x45c\[ngithub.com/onomyprotocol/reserve/x/auction/keeper.(*Keeper).BeginBlocker(0x14002f075f8](http://ngithub.com/onomyprotocol/reserve/x/auction/keeper.(*Keeper).BeginBlocker(0x14002f075f8), {0x1071049e0, 0x1400222c708})\n\t/Users/donglieu/112024/reserve/x/auction/keeper/abci.go:16 +0x11c\[ngithub.com/onomyprotocol/reserve/x/auction/module.AppModule.BeginBlock({{{0x10711deb8](http://ngithub.com/onomyprotocol/reserve/x/auction/module.AppModule.BeginBlock(%7B%7B%7B0x10711deb8), 0x140019aabe0}}, {{0x10711deb8, 0x140019aabe0}, {0x1070c7e80, 0x140005ca550}, {0x10710ac88, 0x1400033e9a0}, {0x1070e1520, 0x14001bebe00}, ...}}, ...)\n\t/Users/donglieu/112024/reserve/x/auction/module/module.go:156 +0x34\[ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_](http://ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_), {{0x107104b68, 0x108d402e0}, {0x10711e7e8, 0x1400337b980}, {{0x0, 0x0}, {0x140004c5496, 0x9}, 0x30, ...}, ...})\n\t/Users/donglieu/go/pkg/mod/github.com/!dong!lieu/cosmos-sdk@v0.50.8-onomy/types/module/module.go:779 +0x1e8\[ngithub.com/onomyprotocol/onomy/app.(*OnomyApp).BeginBlocker(_](http://ngithub.com/onomyprotocol/onomy/app.(*OnomyApp).BeginBlocker(_), {{0x107104b68, 0x108d402e0}, {0x10711e7e8, 0x1400337b980}, {{0x0, 0x0}, {0x140004c5496, 0x9}, 0x30, ...}, ...})\n\t/Users/donglieu/102024/onomy/app/app.go:326 +0x194\[ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).beginBlock(0x14001362fc8](http://ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).beginBlock(0x14001362fc8), 0x140025f58c0)\n\t/Users/donglieu/go/pkg/mod/github.com/!dong!lieu/cosmos-sdk@v0.50.8-onomy/baseapp/baseapp.go:734 +0xec\[ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).internalFinalizeBlock(0x14001362fc8](http://ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).internalFinalizeBlock(0x14001362fc8), {0x107104b68, 0x108d402e0}, 0x140025f58c0)\n\t/Users/donglieu/go/pkg/mod/github.com/!dong!lieu/cosmos-sdk@v0.50.8-onomy/baseapp/abci.go:760 +0xbc0\[ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).FinalizeBlock(0x14001362fc8](http://ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).FinalizeBlock(0x14001362fc8), 0x140025f58c0)\n\t/Users/donglieu/go/pkg/mod/github.com/!dong!lieu/cosmos-sdk@v0.50.8-onomy/baseapp/abci.go:884 +0x2c8\[ngithub.com/cosmos/cosmos-sdk/server.cometABCIWrapper.FinalizeBlock({{0x112d156d8](http://ngithub.com/cosmos/cosmos-sdk/server.cometABCIWrapper.FinalizeBlock(%7B%7B0x112d156d8), 0x14001394608}}, {0x107104ba0, 0x108d402e0}, 0x140025f58c0)\n\t/Users/donglieu/go/pkg/mod/github.com/!dong!lieu/cosmos-sdk@v0.50.8-onomy/server/cmt_abci.go:44 +0x54\[ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0x14003c16540](http://ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0x14003c16540), {0x107104ba0, 0x108d402e0}, 0x140025f58c0)\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/abci/client/local_client.go:185 +0xf8\[ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0x14003c10f18](http://ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0x14003c10f18), {0x107104ba0, 0x108d402e0}, 0x140025f58c0)\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/proxy/app_conn.go:104 +0x1d0\[ngithub.com/cometbft/cometbft/state.(*BlockExecutor).applyBlock(_](http://ngithub.com/cometbft/cometbft/state.(*BlockExecutor).applyBlock(_), {{{0xb, 0x0}, {0x140018a9be9, 0x7}}, {0x140018a9c00, 0x9}, 0x1, 0x2f, {{0x14004c71d40, ...}, ...}, ...}, ...)\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/state/execution.go:224 +0x3c0\[ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyVerifiedBlock(_](http://ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyVerifiedBlock(_), {{{0xb, 0x0}, {0x140018a9be9, 0x7}}, {0x140018a9c00, 0x9}, 0x1, 0x2f, {{0x14004c71d40, ...}, ...}, ...}, ...)\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/state/execution.go:202 +0xd8\[ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0x14000d3ea88](http://ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0x14000d3ea88), 0x30)\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:1772 +0xd50\[ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0x14000d3ea88](http://ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0x14000d3ea88), 0x30)\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:1682 +0x2c0\[ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()](http://ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1())\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:1617 +0xb8\[ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0x14000d3ea88](http://ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0x14000d3ea88), 0x30, 0x0)\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:1655 +0xd90\[ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0x14000d3ea88](http://ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0x14000d3ea88), 0x14002ef2410, {0x1400229ac30, 0x28})\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:2335 +0x26c0\[ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0x14000d3ea88](http://ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0x14000d3ea88), 0x14002ef2410, {0x1400229ac30, 0x28})\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:2067 +0x50\[ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0x14000d3ea88](http://ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0x14000d3ea88), {{0x1070d0780, 0x140015a8378}, {0x1400229ac30, 0x28}})\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:929 +0x5c0\[ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0x14000d3ea88](http://ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0x14000d3ea88), 0x0)\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:836 +0x7bc\ncreated by [github.com/cometbft/cometbft/consensus.(*State).OnStart](http://github.com/cometbft/cometbft/consensus.(*State).OnStart) in goroutine 370\n\t/Users/donglieu/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:398 +0x1e4\n"`

**Comment by DongLieu** [comment]
apphash:

![image](https://github.com/user-attachments/assets/94c199d8-7801-4c3b-a5c6-093f411ea0b4)
